package com.example.bandungzoochatbot;

public class AnimalsData {
    private final String[] fact1 = {
//            "Menghabiskan sebagian besar waktunya menggali untuk menemukan serangga dan cacing",
//            "Gadingnya dapat tumbuh menembus tengkoraknya",
//            "Memiliki tanduk panjang melengkung ke atas",
//            "Bekantan jantan menggunakan hidungnya yang berdaging dan menggantung untuk menarik pasangan",
//            "Memiliki cakar yang kuat dan sirip seperti kaki belakang",
//            "Suka menyendiri",
//            "Memiliki bau khas seperti pandan atau popcorn",
//            "Burung terbesar di dunia. Tingginya dapat mencapai 2,5 meter dengan berat badan 100-120 kg",
            "Pelompat yang hebat, dapat melewati pagar setinggi dua meter dengan mudah",
//            "Memiliki daya ingat yang kuat",
//            "Mampu berlari hingga kecepatan 65 km/jam",
//            "Mampu meniru suara manusia",
//            "Mammalia tertinggi, dengan tinggi dapat mencapai 5 meter",
            "Memiliki paruh yang berat",
//            "Tidak memiliki pita suara",
            "Pandai memanjat tebing",
            "Mudah beradaptasi pada habitat yang berubah",
            "Memiliki kulit yang tebal dan keras untuk berlindung dari serangan predator",
            "Menggonggong seperti anjing",
//            "Memiliki indra penciuman yang tajam, bisa mencium aroma atau bau sampai jarak 5 hingga 11 kilometer",
//            "Memiliki jambul berwarna keemasan yang khas mirip mahkota",
//            "Tidur sambal berdiri",
//            "Mampu menahan nafas selama 5 menit",
//            "Dapat membuat lubang dan sarangnya dengan kedalaman lima meter di dalam tanah",
//            "Memiliki ekor seperti monyet",
//            "Bulunnya tertutupi struktur kecil menyerupai kristal",
//            "Punuknya menyimpan lemak untuk keperluan nutrisi",
//            "Hewan yang sangat cerdas",
//            "Dapat terbang dalam waktu yang lama",
//            "Memiliki kebiasaan mencuci makanan yang didapat",
//            "Usianya dapat mencapai 70 tahun",
//            "Memiliki tanduk yang sangat kuat",
//            "Beristirahat atau tidur dengan menyangga tubuhnya di pepohonan",
//            "Bisa mendengar mangsa dari jarak 1,6 km",
//            "Berkomunikasi dengan cara  saling menyentuh hidung dan menjilat",
//            "Suka menggendong anaknya di dalam kantung",
            "Memiliki tanduk yang dapat tumbuh hingga 2,5 meter dengan diameter 71 cm",
//            "Hidup berkelompok",
            "Tidur dengan berdiri"};
    private final String[] fact2 = {
//            "Mampu terbang dengan kuat namun lebih sering berlari",
//            "Tidak memiliki tulang hidung",
//            "Tanduknya berfungsi untuk mempertahankan diri dari serangan predator",
//            "Lahir dengan wajah biru dan bertransisi ke warna abu-abu antara usia 2,5 dan 8,5 bulan",
//            "Bisa berenang pada usia dua bulan",
//            "Memiliki lidah yang sangat panjang pada 20 – 25cm",
//            "Hewan mammalia dengan ekor terpanjang",
//            "Hewan berkaki dua paling cepat. Dapat berlari hingga kecepatan 50 kilometer per jam",
            "Kukunya melebar dan berbunyi klik karena bobot hewan yang besar.",
//            "Perenang yang hebat",
//            "Setiap harimau memiliki pola garis yang berbeda",
//            "Pemakan serangga dan penyebar benih",
//            "Hanya membutuhkan 5 hingga 30 menit waktu tidur dalam satu hari",
            "Memiliki cula berwarna merah pada jantan dan kuning pada betina",
//            "Memiliki jambul yang menunjukkan suasana hatinya",
            "Memiliki dua lapisan bulu agar tidak kedinginan",
            "Fakta unik kangkareng perut putih",
            "Mampu berlari sangat cepat dan melompat tinggi",
            "Hanya membutuhkan waktu beristirahat selama 3 jam saja",
//            "Memiliki racun yang mematikan",
//            "Mencari makan dengan menghentakan kakinya ke tanah atau rerumputan",
//            "Tidak bisa bersendawa, muntah, atau bernapas melalui mulut",
//            "Memproduksi tabir surya mereka sendiri",
//            "Durinya penuh nutrisi",
//            "",
//            "Memiliki ekor mempesona untuk menarik perhatian betina",
//            "Dapat menahan haus selama berminggu-minggu",
//            "Suka tidur",
//            "Saat terbang membentuk formasi huruf “V”",
//            "Hewan sangat cerdas",
//            "Burung yang setia terhadap pasangannya",
//            "Dapat mengubah warna mata",
//            "Tidak memiliki ekor",
//            "Bisa menghabiskan 18-20 jam sehari untuk tidur",
//            "",
//            "Memiliki sepasang kaki belakang yang besar dan sangat kuat",
            "Sitatunga Hewan rumanisia",
//            "Panjang badannya dapat mencapai 2,4 meter dan berat 290 kg",
            "Setiap zebra memiliki garis tubuh yang unik seperti sidik jari manusia"};
    private final String[] description = {
//            "Merupakan spesies dari keluarga Numididae yang paling populer. Memiliki habitat asli di Afrika terutama di selatan Sahara. Biasanya dipelihara untuk diambil daging dan telurnya. Memiliki ciri khas bulu  berwarna abu-abu kegelapan dengan bintik putih seperti mutiara.",
//            "Merupakan spesies babi yang berhabitat di hutan-hutan tropis dan daerah rawa-rawa di berbagai wilayah Indonesia, Malaysia, dan Thailand. Memiliki ciri khas tanduk panjang yang melengkung ke atas dan ke belakang pada jantan dewasa. Makanan mereka adalah tumbuhan, akar, buah-buahan, dan bahkan serangga.",
//            "Merupakan satwa endemik yang hanya dapat ditemukan di pulau Jawa. Pada umumnya berada di hutan, lahan pertanian dan daerah rerumputan. Pada pagi hari, biasanya banteng akan mendatangi daerah rerumputan untuk mencari makan. Ketika matahari sudah terik, mereka akan memanfaatkan waktunya untuk mencari sumber air dan menepi untuk beristirahat. Waktu reproduksi Banteng Jawa ada di malam hari, dan mereka termasuk kedalam jenis satwa monoestroes atau memiliki satu musim kawin dalam setahun yang hanya terjadi pada bulan Juli hingga November.",
//            "Merupakan satwa endemik Pulau Kalimantan. Pada spesies jantan memiliki hidung panjang dan besar. Ukurannya dapat mencapai 75 cm dengan berat mencapai 24 kg. Kera Bekantan betina berukuran sekitar 60 cm dengan berat 12 kg. Makanan yang dikonsumsi adalah buah-buahan, biji-bijian dan dedaunan.",
//            "Merupakan hewan mamalia semi-akuatik. Memiliki ciri khas tubuh ramping dengan ekor panjang dan leher yang panjang. Biasa ditemukan di daerah berair seperti sungai, danau, dan rawa-rawa. Makanannya adalah ikan, amfibi, invertebrata air, dan kadang-kadang mamalia kecil.",
//            "Memiliki bulu yang tebal dan lebat, dengan warna yang bervariasi antara cokelat gelap, cokelat kemerahan, hingga keemasan. Memiliki kebiasaan memakan madu dan sering mendatangi sarang lebah untuk mengumpulkan madu. Makanan yang dikonsumsi adalah serangga, buah-buahan, madu, dan kadang-kadang mengambil telur atau mamalia kecil.",
//            "Berhabitat di negara Indonesia, Malaysia, Thailand, dan Filipina. Ciri khasnya adalah ekor yang panjang dan prehensil, yang artinya dapat digunakan untuk memegang benda atau memanjat pohon. Binturong adalah hewan omnivora dan hidup nokturnal.",
//            "Burung unta  termasuk dalam famili Struthionidae dan merupakan anggota dari ordo Struthioniformes. Mereka memiliki kepala kecil dengan paruh yang lebar dan kuat, yang digunakan untuk mencabik dan mengunyah makanan. Burung unta tidak bisa terbang karena mereka memiliki sayap yang pendek dan tidak dapat mendukung tubuh mereka yang besar. Makanan burung unta adalah tumbuhan seperti rumput, daun, dan biji-bijian. Mereka juga dapat mengkonsumsi benda-benda non-makanan seperti batu dan kerikil untuk membantu pencernaan mereka. Telur burung unta sangat besar dan memiliki cangkang yang tebal, yang menjadikannya tahan terhadap kerusakan dan perlindungan terhadap suhu ekstrem.",
            "Merupakan spesies mamalia yang dapat ditemukan di berbagai wilayah Afrika. Berat Eland bisa mencapai lebih dari satu ton. Eland adalah hewan yang herbivora. Eland hidup dalam kelompok besar yang terdiri dari beberapa betina dan anak-anak mereka, sementara jantan biasanya hidup sendiri atau dalam kelompok kecil. ",
//            "Gajah adalah hewan mamalia terbesar di daratan. Memiliki dua gigi taring panjang yang disebut gading yang tumbuh dari rahang atas, digunakan untuk berbagai mencari makanan, menggali air, membela diri, dan berkomunikasi dengan sesama gajah. Gajah memiliki belalai yang berfungsi untuk mengambil makanan seperti daun, rumput, buah-buahan, serta untuk minum dan mandi.",
//            "Merupakan salah satu predator terbesar dan terkuat di dunia. Panjang tubuhnya dapat mencapai 3 meter, dengan ekor sekitar 1 meter, dan berat mencapai 200 hingga 300 kilogram. Bulu mereka yang lebat dan kasar memberikan perlindungan dan juga membantu mereka menyamar di lingkungan hutan dan padang rumput. Harimau umumnya memangsa hewan besar seperti rusa, babi hutan, dan sapi liar.",
//            "Jalak Bali adalah burung endemik yang hanya ditemukan di pulau Bali. Burung ini memiliki ukuran sedang dengan tubuh yang kompak dan paruh yang kuat. Mereka mampu meniru suara berbagai jenis burung dan bahkan suara manusia. Burung Jalak biasanya mencari makan di pohon-pohon dan tanah, memakan beragam jenis makanan, termasuk serangga, buah-buahan, biji-bijian, dan nektar.",
//            "Merupakan hewan terbesar di daratan dengan tinggi tubuh yang mencapai 5 hingga 6 meter. Jerapah menggunakan leher mereka yang panjang untuk mencapai daun-daun yang sulit dijangkau oleh hewan lain di atas pohon. Kaki-kaki mereka panjang membantu mereka berlari dengan kecepatan hingga 55 kilometer per jam. Mereka juga memiliki lidah yang kuat untuk membela diri dari predator.",
            "Julang Sulawesi adalah primata yang endemik di pulau Sulawesi. Mereka adalah anggota keluarga kera. Ciri khasnya adalah jambul yang menonjol di atas kepala, yang memberikan julukan “jilang” kepada spesies ini. Hewan ini hidup di hutan-hutan tropis dan hutan dataran rendah. Julang Sulawesi adalah makhluk arboreal, yang berarti mereka lebih sering berada di atas pohon.",
//            "Kakatua bisa ditemukan di berbagai wilayah Australia, Papua Nugini, dan Kepulauan Solomon. Ciri khas kakatua adalah paruh yang kuat dan melengkung untuk makan, memanjat, dan membantu dalam kegiatan sehari-hari. Kakatua memiliki kemampuan untuk meniru suara manusia dan suara burung lainnya. Makanan utama mereka adalah biji-bijian, buah-buahan, bunga, nektar, dan serangga.",
            "Kambing Gunung adalah anggota keluarga kambing yang tinggal di daerah pegunungan di berbagai belahan dunia. Kambing Gunung memiliki tubuh yang kekar dengan kaki yang kuat dan tajam serta cakar yang tajam, serta mantel bulu yang tebal dan kaku untuk melindungi mereka dari suhu dingin. Kambing Gunung adalah hewan herbivora, makanannya adalah rumput, daun, dan tunas.",
            "Merupakan spesies burung rangkong yang terdapat di India, Nepal, Bhutan, Bangladesh, Myanmar, Cina, Vietnam, Kamboja, Thailand, Malaysia, Singapura, dan Indonesia. Habitatnya terdiri dari hutan primer yang masih terjaga ekosistemnya. Tubuh Kangkareng Perut Putih berukuran 55-60 cm. Paruh mulai terbentuk pada bulan usia 1-2 sejak anakan dan akan terbentuk sempurna memasuki bulan ke 12-14. Makanan mereka adalah buah-buahan dan hewan kecil seperti serangga, ikan, kelelawar, katak, kadal, ular, dan kalajengking.",
            "Meripakan burung berukuran besar yang berasal dari Papua Nugini dan pulau Papua. Tubuhnya dapat mencapai tinggi 1,5 hingga 1,8 meter. Ciri khasnya adalah mahkota berbentuk kasing di atas kepala yang terbuat dari tanduk keras yang disebut “casque”, berfungsi sebagai perlindungan dan alat berkomunikasi. Mereka adalah hewan omnivore.",
            "Kijang adalah hewan mamalia yang memiliki ciri khas berupa tanduk. Mereka dapat berlari dan melompat dengan lincah. Kijang termasuk hewan herbivora dan makanannya terdiri dari berbagai jenis tanaman, seperti rumput, daun, tunas, dan buah-buahan. Kijang menghabiskan sebagian besar waktunya mencari makan dan menggembalakan di padang rumput atau hutan terbuka.",
//            "Merupakan spesies kadal terbesar di dunia dengan panjang tubuh mencapai 3 meter atau lebih dan berat mencapai 70. Biasa ditemukan di beberapa pulau di Indonesia, terutama di Pulau Komodo, Rinca, Flores, Gili Motang, dan Gili Dasami. Gigi mereka yang besar dan tajam merupakan senjata utama mereka, Lidah yang bercabang dan dapat mendeteksi aroma mangsa dari jarak jauh. Komodo biasanya memangsa rusa, babi hutan, kera, dan burung. Mereka dapat menggunakan kepekaan mereka terhadap aroma dan gerakan untuk menemukan mangsa, serta kemampuan bersembunyi dengan baik di vegetasi dan di bawah pepohonan.",
//            "Kroonkran adalah burung asli Afrika bagian timur dan selatan. Memiliki mahkota bulu emas yang unik di atas kepalanya, digunakan dalam pertunjukan pacaran, di mana burung bangau melakukan tarian, lompatan, dan seruan yang rumit untuk menarik pasangan. Lehernya yang panjang memungkinkan mereka mencari makan di air dangkal dan rerumputan tinggi.",
//            "Merupakan mamalia herbivora yang memiliki tubuh yang kokoh dan kuat, dengan rambut yang biasanya terdiri dari bulu-bulu kasar. Mereka memiliki mulut yang kuat dengan gigi-gigi yang dirancang untuk mengunyah dan mencerna makanan tumbuhan serat seperti rumput, jerami, dan biji-bijian. Kuda adalah hewan yang cerdas dan dapat dilatih dengan baik untuk memahami perintah dan berinteraksi dengan manusia.",
//            "Kuda Nil adalah mamalia air yang berhabitat di Afrika Sub-Sahara. Merupakan hewan semiaquatic, yaitu menghabiskan sebagian besar waktunya di sungai, danau, atau kolam air yang dalam. Mereka bisa berenang dengan sangat baik dan bahkan tidur di dalam air dengan hanya hidung dan telinga yang terlihat di permukaan. Kuda Nil adalah hewan yang cukup agresif, mereka menyerang dengan gigi dan taring mereka yang tajam jika merasa terancam.",
//            "Landak Jawa adalah hewan pengerat yang terdapat di Jawa dan Bali. Landak Jawa memiliki tubuh berukuran sekitar 60 hingga 80 cm, ditambah dengan ekor pendek sekitar 15 hingga 25 cm. Duri-duri yang menonjol di kulit dapat mencapai panjang 20 cm dan digunakan sebagai pertahanan untuk melindungi diri. Makanan utama Landak Jawa adalah tumbuhan, buah-buahan dan biji-bijian.",
//            "Merupakan primata yang endemik di Pulau Jawa. Makanan utamanya adalah daun, tunas, dan buah-buahan. Mereka memiliki perut yang kompleks yang memungkinkan mereka untuk mencerna serat tumbuhan yang sulit dicerna. Kelompok lutung Jawa sering terlihat bergerak melalui pohon-pohon dalam pencarian makanan dan berkomunikasi dengan menggunakan panggilan khusus.",
//            "Merak merupakan burung asli India dan Sri Lanka. Panjang tubuhnya sekitar 1-2 meter, dan ekornya mencapai 1,5 meter. Saat kawin atau menunjukkan kegembiraan, merak dapat mengembangkan ekornya menjadi lingkaran besar yang memukau. Merak adalah burung omnivora , sering ditemukan di hutan terbuka, padang rumput, dan daerah agraris.",
//            "Onta adalah hewan asli daerah Timur Tengah dan Afrika Utara. Mereka dapat berlari dengan kecepatan hingga 65 kilometer per jam. Ciri khasnya adalah punuk di bagian punggung yang berfungsi sebagai cadangan lemak dan sumber energi saat makanan tidak tersedia. Onta memiliki bulu yang tebal untuk melindungi mereka dari panas matahari dan pasir.",
//            "Merupakan hewan endemik pulau Sumatra dan Kalimantan. Berat badannya bisa mencapai 90 kilogram. Orangutan hidup di hutan hujan tropis dan sebagian besar waktu dihabiskan di pohon. Mereka memiliki kemampuan yang luar biasa untuk menggunakan alat, seperti daun sebagai payung, ranting sebagai alat pendukung, dan bahkan menggunakan batang kayu sebagai alat untuk mencari makan.",
//            "Pelikan memiliki ciri khas kantung tenggorokan yang besar di bagian bawah paruh, untuk memperluas dan menampung ikan atau mangsa lain yang mereka tangkap. Makanan utamanya adalah ikan, amfibi, dan burung kecil. Mereka berburu dengan cara menyelam ke dalam air dari udara atau melayang di atas air. Pelikan sering ditemukan di dekat perairan seperti sungai, danau, atau pantai.",
//            "Rakun merupakan mamalia asli Amerika Utara, tetapi juga ditemukan di Eropa dan Jepang. Panjang tubuh mereka berkisar antara 40 hingga 70 cm, ditambah dengan ekor yang dapat mencapai panjang 20 hingga 40 cm. Rakun adalah hewan yang sangat adaptif dan sering ditemukan di berbagai habitat seperti hutan, daerah subur, dan perkotaan. Mereka adalah hewan omnivora dan makanannya adalah serangga, buah-buahan, biji-bijian, ikan, dan amfibi.",
//            "Rangkong badak merupakan burung endemik di wilayah Asia Tenggara. Ukuran tubuhnya hingga 1 meter dan berat mencapai 2 hingga 3 kilogram. Memiliki tanduk yang digunakan untuk komunikasi antarindividu dan ritual perkawinan. Rangkong badak sering ditemukan di hutan-hutan lebat dan hutan dataran rendah. Makanan utama rangkong badak adalah buah-buahan, serangga, reptil kecil, mamalia kecil, serta burung-burung kecil.",
//            "Rusa adalah hewan herbivora yang yang tersebar di dunia. Mereka bisa memiliki bulu tebal dan berlapis-lapis saat musim dingin, sementara bulu mereka bisa lebih tipis saat musim panas. Rusa sering ditemukan di daerah berhutan, savana, atau padang rumput terbuka. Masa hidup rusa umumnya sekitar 10 hingga 20 tahun.",
//            "Siamang adalah jenis monyet yang berasal dari hutan-hutan tropis di Asia Tenggara. Ukuran tubuhnya sekitar 60 hingga 90 sentimeter, dan beratnya sekitar 10 hingga 14 kilogram. Ciri khas siamang adalah adanya jaringan kulit yang menghubungkan dua jari tengah, memberikan kemampuan untuk melompat dengan lincah di antara cabang-cabang pohon. Mereka juga memiliki lengan yang panjang dan kuat untuk melompat di pohon-pohon tinggi.",
//            "Singa keluarga kucing besar dan ditemukan di berbagai bagian Afrika dan beberapa wilayah di Asia. Singa jantan memiliki panjang tubuh sekitar 1,7 hingga 2,5 meter, dengan berat mencapai 150 hingga 250 kilogram, sedangkan panjang tubuh betina sekitar 1,4 hingga 1,8 meter dan berat sekitar 120 hingga 180 kilogram. Mereka adalah pemangsa puncak dan berburu hewan herbivora seperti impala, zebra, dan kerbau.",
            "Sitatunga adalah hewan ruminansia yang terdapat di beberapa wilayah di Afrika. Mereka adalah jenis antelop yang memiliki adaptasi khusus untuk hidup di daerah rawa-rawa dan lahan basah. Sitatunga memiliki tinggi bahu sekitar 100 hingga 150 sentimeter dan berat mencapai 80 hingga 150 kilogram. Sitatunga memiliki ciri unik berupa kaki yang dilengkapi dengan kelenjar keringat khusus, yang memungkinkan mereka melepaskan bau yang kuat untuk menandai wilayah dan mengkomunikasikan keberadaan mereka. Sitatunga adalah hewan herbivora dan makanan utamanya adalah rumput, daun, pucuk, dan tanaman air. dengan lingkungan rawa-rawa yang berair dan lembab.",
//            "Walabi adalah hewan marsupial yang terkenal dan ditemukan di Australia dan beberapa wilayah di Papua Nugini. Memiliki panjang tubuh sekitar 1 hingga 1,6 meter, dengan ekor tambahan sekitar 1 meter, dan berat mencapai 20 hingga 90 kilogram. Ciri khas walabi adalah adanya kantung di perut betina yang berfungsi sebagai tempat mengandung dan menyusui anak-anak mereka. Mereka memiliki kaki belakang yang kuat dan cakar yang berguna untuk melompat jauh dan bergerak dengan cepat di daratan.",
            "Wildebeest biru adalah mamalia yang merupakan hewan endemik di Afrika Timur dan ditemukan terutama di padang rumput dan savana. Memiliki tinggi bahu sekitar 1,2 hingga 1,5 meter dan berat mencapai 180 hingga 270 kilogram. Hewan ini dikenal karena migrasi massalnya yang spektakuler, ribuan bahkan jutaan wildebeest biru bergerak bersama dengan zebra dan antelop lainnya untuk mencari rumput segar dan sumber air. Wildebeest biru adalah hewan herbivora dan makanan utamanya adalah rumput dan tanaman rendah lainnya. Mereka mengandalkan adaptasi khusus untuk mencerna makanan serat kasar dan dapat berjalan jarak yang jauh untuk mencari sumber makanan yang cukup.",
    };

    public String[] getFact1() {
        return fact1.clone();
    }

    public String[] getFact2() {
        return fact2.clone();
    }

    public String[] getDescription() {
        return description.clone();
    }

}
